### PR TITLE
Added TLS Files

### PR DESCRIPTION
**Pull request by CodyAu**
Added XML files so that you can import traffic light timings for the St. Vital area (also includes a road net file with modified intersections for the St. Vital area)

### CODE REVIEW

**Review by Sahmwell — COMMENTED** [review]
I noticed that you have each file in TrainingGym/Scenerios/StVitalTrafficLights, and also in Individual_Code/Cody/Traffic_Light_Imports/StVital_TrafficLights. Is there a benefit to having a second copy?

**Comment by CodyAu** [comment]
Not particularly, besides serving as a clean backup since netedit can mess up xml files randomly. I just thought that I was supposed to upload files from individual tasks to my individual folder as well.

**Comment by Sahmwell** [comment]
Ah, yeah I think it's okay to just keep one copy then, I think that the more comfortable we get with git should make it so we don't need more backups since we can store exactly what we want to keep in commits

**Comment by CodyAu** [comment]
Sounds good, I removed the extra copies now

**Review by nazric — APPROVED** [review]
Looks good to me

**Pull request merged**
